sudo: false
language: perl
perl:
  - "5.20"
  - "5.16"
  - "5.10"
env:
  - "HARNESS_OPTIONS=j1 TEST_POD=1"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage EV"
  - "cpanm -n https://github.com/jhthorsen/mojo-irc/archive/master.tar.gz"
  - "cpanm -n --installdeps ."
notifications:
  email:
    recipients:
      - jhthorsen@cpan.org
    on_failure: always
    on_success: change
  irc:
    channels: "chat.freenode.net#convos"
    on_failure: always
    on_success: change
